routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/** * Admin routes
 */
Route::namespace('Admin')->group(function () {
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'LoginController@login')->name('admin.login');
    Route::get('admin/logout', 'LoginController@logout')->name('admin.logout');
});
Route::group(['prefix' => 'admin', 'middleware' => ['employee'], 'as' => 'admin.' ], function () {
    Route::namespace('Admin')->group(function () {
            Route::post('getcategory', 'Products\ProductController@getCategory')->name('admin.getcategory');
            Route::get('/', 'DashboardController@index')->name('dashboard');
            Route::namespace('Products')->group(function () {
                Route::resource('products', 'ProductController');
                Route::get('remove-image-thumb/{id}', 'ProductController@removeThumbnail')->name('product.remove.thumb');
                Route::get('products-search', 'ProductController@index')->name('products.search');
                Route::get('stock-products', 'ProductController@stocklist')->name('stocklist.products');
                Route::get('editstock/products/{id}', 'ProductController@stockedit')->name('stockedit.products');
                Route::post('updatestock/products', 'ProductController@stockupdate')->name('stockupdate.products');
            });

            Route::namespace('Categories')->group(function () {
                Route::resource('categories', 'CategoryController');
                Route::get('remove-image-category', 'CategoryController@removeImage')->name('category.remove.image');
                Route::get('categories-search', 'CategoryController@index')->name('categories.search');
                Route::get('category-child/{parent_id}', 'CategoryController@childCategory')->name('category.child');
            });
            

            //News
            Route::get('news','News\NewsController@create')->name('news.create');
            Route::post('news-store','News\NewsController@store')->name('news.store');
            Route::get('news-list','News\NewsController@index')->name('news.list');
            Route::get('news/delete/{id}','News\NewsController@destroy')->name('news.destroy'); 
            Route::get('news/edit/{id}','News\NewsController@edit')->name('news.edit');
            Route::get('news-search','News\NewsController@index')->name('news.search');
            Route::post('news/status/{id}', 'News\NewsController@status')->name('news.status');

            
            Route::resource('employees', 'EmployeeController');
            Route::post('employees/is_active/{id}', 'EmployeeController@is_active')->name('employees.is_active');
            Route::get('profile/{id}', 'EmployeeController@getProfile')->name('employee.profile');
            Route::put('profile/{id}', 'EmployeeController@updateProfile')->name('employee.profile.update');
            Route::resource('permissions', 'Permissions\PermissionController');

            //CMS
            Route::get('cms-create','Cms\CmsController@create')->name('cms.create');
            Route::post('cms-store','Cms\CmsController@store')->name('cms.store');
            Route::get('cms','Cms\CmsController@index')->name('cms.list');
            Route::post('cms/delete/{id}','Cms\CmsController@destroy')->name('cms.destroy'); 
            Route::get('cms/edit/{id}','Cms\CmsController@edit')->name('cms.edit');
            Route::post('cms/status/{id}', 'Cms\CmsController@status')->name('news.status');

            //ContactUs
            Route::get('contactus-list','ContactusController@index')->name('contactus.list');
            Route::post('contactus/delete/{id}','ContactusController@destroy')->name('contactus.destroy'); 

    });    
});

/**
 * Frontend routes unused
 */

Route::namespace('Customer')->group(function () {
    Route::get('/', 'HomeController@index')->name('customer.home');
    // Contact Us
    Route::get('/contact-us', 'ContactUsController@index')->name('customer.contactus');
    Route::post('/contact-us/save', 'ContactUsController@store')->name('customer.contactus_save');

    // Gallery
    Route::get('/gallery', 'GalleryController@index')->name('customer.gallery');

    // Category Listing
    Route::get('/category-listing', 'CategoryController@index')->name('customer.category_listing');
    Route::post('/get-category-list', 'CategoryController@getCategoryList')->name('customer.get_category_list');
    Route::post('/get-product-model', 'CategoryController@getProductModel')->name('customer.get_product_model');

    // About us
    Route::get('/about-us', 'AboutController@index')->name('customer.aboutus');

    
});

resources/views/admin/roles/create.blade.php
@extends('layouts.admin-sol.app')
@section('content')
	<div class="container-fluid">
		<div class="row bg-title">
			<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
				<h4 class="page-title">Manage Venders</h4> </div>
			<!-- <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
				<ol class="breadcrumb">
					<li><a href="#">Manage Products</a></li>
					<li class="active">Add Products</li>
				</ol>
			</div> -->
			<!-- /.col-lg-12 -->
		</div>
		<div class="page-content">
			<div class="row">
				<div class="col-sm-12">
					<div class="product-tab">
						<ul class="nav nav-tabs" data-spy="affix" data-offset-top="135">
							<li><a href="{{ route('admin.employees.create') }}">Add Vender</a></li>
							<li><a href="{{ route('admin.employees.index') }}">Vendor's Listing</a></li>
							<li><a href="{{ route('admin.roles.index') }}">Roles</a></li>
							@if(isset($roles->id))
							<li class="active"><a href="#" class="">Edit Roles</a></li>
							@else
							<li class="active"><a href="{{ route('admin.roles.create') }}" class="">Add Roles</a></li>
							@endif
					  </ul>
					  <div class="tab-content">
							<div id="AddProcucts" class="tab-pane fade in active">
								<div class="add-product">
									<form action="{{ route('admin.roles.store') }}" method="post" class="form">
										<div class="box-body">
											{{ csrf_field() }}
											<div class="row">
												<input type="hidden" name="id" value="@if(isset($roles->id)){{$roles->id}}@endif">
												<div class="col-lg-5 col-md-6 col-sm-6">
													<div class="form-group">
														<label for="display_name"> Name</label>
														<input type="text" name="name" id="display_name" placeholder="Name" class="form-control" maxlength="100" value="@if(isset($roles->name)){{$roles->name}}@elseif(old('name')!=''){{old('name')}} @endif">
														@if($errors->has('name'))
					                                    	<span class="text-danger">{{$errors->first('name')}}</span>
					                                    @endif
													</div>
												</div>
												<div class="col-lg-5 col-md-6 col-sm-6">
													<div class="form-group">
														<label for="description">Description</label>
														<textarea name="description" id="description" class="form-control ckeditor" maxlength="500" placeholder="Description">@if(isset($roles->description)){{$roles->description }}@elseif(old('description')!=''){{old('description')}} @endif</textarea>
														@if($errors->has('description'))
					                                    	<span class="text-danger">{{$errors->first('description')}}</span>
					                                    @endif
													</div>
												</div>
												<div class="col-lg-10 col-md-12 col-sm-12">
												<div class="form-group">
													<label for="permissions">Permissions</label>
													{{-- <select name="permissions[]" id="permissions" class="form-control select2" multiple="multiple">
													@foreach($permissions as $permission)
														<option @if(isset($permission_role))
														@foreach($permissions_role as $permission_role)
													 		@if($permission_role->permission_id == $permission->id ) selected= "selected" @endif value="{{ $permission->id }}"
											 		 	@endforeach
											 		 	@endif
											 		 	value="{{$permission->id}}"
											 		 	>
										 		 	 	{{$permission->name}}</option>
													@endforeach
													</select>
													@if($errors->has('permissions'))
				                                    	<span class="text-danger">{{$errors->first('permissions')}}</span>
				                                    @endif --}}
												</div>
											</div>
										</div>
										<div class="row">
				                            <div class="col-sm-6 col-md-10 col-sm-6 col-xs-12">
				                                <div class="form-group">
				                                    <table  class="table table-striped" id="permission">
				                                        <thead>
				                                            <th>Sr No</th>
				                                            <th>Modules</th>
				                                            <th> View <input type="checkbox" onClick="viewAll(this)" class="role-check-box"></th>
				                                            <th> Add <input type="checkbox" onClick="addAll(this)" class="role-check-box"></th>
				                                            <th> Edit <input type="checkbox" onClick="editAll(this)" class="role-check-box"></th>
				                                            <th> Delete <input type="checkbox" onClick="deleteAll(this)" class="role-check-box"></th>
				                                        </thead>
				                                        <tbody>
			                                            @foreach($modules as $module)
			                                                <tr>
			                                                    <td><input type="hidden" name="module_id[]" value="{{ $module->id }}"> {{ $module->id }} </td>
			                                                    <td>{{ $module->display_name }} </td>
			                                                    <td align="center"><input type="checkbox" name="view[]" value="1-{{$module->name}}" 
		                                                    	@if(isset($permissions_roles))
		                                                    	@foreach($permissions_roles as $permissions_role)  		@if($permissions_role->module_id==$module->id && $permissions_role->view==1)
		                                                    	 	checked 
		                                                    		@endif
			                                                    @endforeach
			                                                    @endif></td>
			                                                    <td align="center"><input type="checkbox" name="add[]" value="1-{{$module->name}}"
		                                                    	@if(isset($permissions_roles))
		                                                    	@foreach($permissions_roles as $permissions_role)  		@if($permissions_role->module_id==$module->id && $permissions_role->add==1)
		                                                    	 	checked 
		                                                    		@endif
			                                                    @endforeach
			                                                    @endif></td>
			                                                    <td align="center"><input type="checkbox" name="edit[]" value="1-{{$module->name}}"
		                                                    	@if(isset($permissions_roles))
		                                                    	@foreach($permissions_roles as $permissions_role)  		@if($permissions_role->module_id==$module->id && $permissions_role->edit==1)
		                                                    	 	checked 
		                                                    		@endif
			                                                    @endforeach
				                                                @endif></td>
			                                                    <td align="center"><input type="checkbox" name="delete[]" value="1-{{$module->name}}"
			                                                    @if(isset($permissions_roles))
		                                                    	@foreach($permissions_roles as $permissions_role)  		@if($permissions_role->module_id==$module->id && $permissions_role->delete==1)
		                                                    	 	checked 
		                                                    		@endif
			                                                    @endforeach
			                                                    @endif></td>
			                                                </tr>
		                                        	    @endforeach   
				                                        </tbody>
				                                    </table>
				                                </div>
				                            </div>
				                        </div>
										<div class="row">
											<div class="col-sm-12">
												<hr style="height: 1px; background: #e4e4e4;">
											</div>
											<div class="col-sm-12">
												<div class="submit-btn">
													<button type="submit" class="btn btn-submit">Submit</button>
												</div>
											</div>
										</div>
									</form>
								</div>
					 	 	</div>
						</div>
					</div>
				</div>
			</div>
		</div>
@endsection
@push('js')
<script type="text/javascript">

    function addAll(source) {
        checkboxes = document.getElementsByName('add[]');
        for(var i=0, n=checkboxes.length;i<n;i++) {
            checkboxes[i].checked = source.checked;
        }
    }
 	function viewAll(source) {
        checkboxes = document.getElementsByName('view[]');
        for(var i=0, n=checkboxes.length;i<n;i++) {
            checkboxes[i].checked = source.checked;
        }
    }
    function editAll(source) {
        checkboxes = document.getElementsByName('edit[]');
        for(var i=0, n=checkboxes.length;i<n;i++) {
            checkboxes[i].checked = source.checked;
        }
    }
    function deleteAll(source) {
        checkboxes = document.getElementsByName('delete[]');
        for(var i=0, n=checkboxes.length;i<n;i++) {
            checkboxes[i].checked = source.checked;
        }
    }
</script>

resources/views/admin/roles/edit.blade.php
@extends('layouts.admin-sol.app')
@section('content')
	<div class="container-fluid">
		<div class="row bg-title">
			<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
				<h4 class="page-title">Manage Venders</h4> </div>
			<!-- <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
				<ol class="breadcrumb">
					<li><a href="#">Manage Products</a></li>
					<li class="active">Add Products</li>
				</ol>
			</div> -->
			<!-- /.col-lg-12 -->
		</div>
		<div class="page-content">
			<div class="row">
				<div class="col-sm-12">
					@include('layouts.errors-and-messages')
					<div class="product-tab">
						<ul class="nav nav-tabs" data-spy="affix" data-offset-top="135">
							<li><a href="{{ route('admin.employees.create') }}">Add Vender</a></li>
							<li><a href="{{ route('admin.employees.index') }}">Vendor's Listing</a></li>
							<li class="active"><a href="{{ route('admin.roles.index') }}">Roles</a></li>
							<li><a href="{{ route('admin.permissions.index') }}">Permissions</a></li>
					  </ul>
					  
					  <div class="tab-content">
							<div id="AddProcucts" class="tab-pane fade in active">
								<div class="add-product">
								  <form action="{{ route('admin.roles.update', $role->id) }}" method="post" class="form">
								  	<input type="hidden" name="_method" value="put">
										{{ csrf_field() }}
										<div class="row">
											<div class="col-lg-5 col-md-6 col-sm-6">
												<div class="form-group">
													<label for="display_name">Display Name <span class="text text-danger">*</span></label>
													<input type="text" name="display_name" id="display_name" placeholder="Display name" class="form-control" value="{{ old('display_name') ?: $role->display_name }}">
												</div>
											</div>
											<div class="col-lg-5 col-md-6 col-sm-6">
												<div class="form-group">
													<label for="description">Description</label>
													<textarea name="description" id="description" class="form-control ckeditor" placeholder="Description"> {!! old('description') ?: $role->description !!}</textarea>
												</div>
											</div>
											<div class="col-lg-10 col-md-12 col-sm-12">
												<div class="form-group">
													<label for="permissions">Permissions</label>
													<select name="permissions[]" id="permissions" class="form-control select2" multiple="multiple">
														@foreach($permissions as $permission)
															<option @if(in_array($permission->id, $attachedPermissionsArrayIds)) selected="selected" @endif value="{{ $permission->id }}">{{ $permission->display_name }}</option>
														@endforeach
													</select>
												</div>
											</div>
										</div>
										<div class="row">
										<div class="col-sm-12">
											<hr style="height: 1px; background: #e4e4e4;">
										</div>
										<div class="col-sm-12">
											<div class="submit-btn">
												<button type="submit" class="btn btn-submit">Submit</button>
											</div>
										</div>
									</div>
								</form>
							</div>
					  </div>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/admin/roles/list.blade.php
@extends('layouts.admin-sol.app')
@section('content')
	<div class="container-fluid">
		<div class="row bg-title">
			<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
				<h4 class="page-title">Manage Vendors</h4> </div>
			<!-- <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
				<ol class="breadcrumb">
					<li><a href="#">Manage Products</a></li>
					<li class="active">Add Products</li>
				</ol>
			</div> -->
			<!-- /.col-lg-12 -->
		</div>
		@include('layouts.errors-and-messages')
		@if(!$roles->isEmpty())
		<div class="page-content">
			<div class="row">
				<div class="col-sm-12">
					<div class="product-listing">
						<ul class="nav nav-tabs" data-spy="affix" data-offset-top="135">
							@php
	                            $permission = App\Helpers\Permission::permission('roles');
	                        @endphp
							@if($permission->add==1)
							<li><a href="{{ route('admin.employees.create') }}">Add Vender</a></li>
							@endif
							@if($permission->view==1)
							<li><a href="{{ route('admin.employees.index') }}">Vendor's Listing</a></li>
							@endif
							<li class="active"><a>Roles</a></li>
	                        @if($permission->add==1)
							<li><a href="{{ route('admin.roles.create') }}" class="">Add Roles</a></li>
							@endif
					  	</ul>
				  		<div class="tab-content">
							<div id="ProductListing" class="tab-pane fade in active">
								<div class="product-listing">
									<div class="table-responsive">
										<table id="example" class="table border-b1px" style="width:100%">
											<thead>
												<tr>
													<td>Display Name</td>
													<td>Description</td>
													<td>Actions</td>
												</tr>
											</thead>
											<tbody>
											@foreach ($roles as $role)
												<tr>
													<td>
														{{ $role->name }}
													</td>
													<td>
														{!! $role->description !!}
													</td>
													<td>
														<div class="action-btn">
															<form action="{{ route('admin.roles.destroy', $role->id) }}" method="post" class="form-horizontal">
																{{ csrf_field() }}
																<input type="hidden" name="_method" value="delete">
																<div class="btn-group">
	                        									@if($permission->edit==1)
																	<a href="{{ route('admin.roles.edit', $role->id) }}" class="btn btn-edit"><i class="mdi mdi-pencil"></i></a>
																@endif
																@if($permission->delete==1)
																	<button onclick="return confirm('Are you sure? You want to delet.')" type="submit" class="btn btn-delete"><i class="mdi mdi-close"></i></button>
																@endif
																</div>
															</form>
														</div>
													</td>
												</tr>
											@endforeach
											</tbody>
										</table>
									</div>
								</div>
							</div>
					  </div>

					</div>
				</div>
			</div>
		</div>
		@endif
	</div>
@endsection
@section('js')
<script>
	$(document).ready(function() {
		$('#example').DataTable();
	} );
</script>
@endsection