routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/** * Admin routes
 */
Route::namespace('Admin')->group(function () {
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'LoginController@login')->name('admin.login');
    Route::get('admin/logout', 'LoginController@logout')->name('admin.logout');
});
Route::group(['prefix' => 'admin', 'middleware' => ['employee'], 'as' => 'admin.' ], function () {
    Route::namespace('Admin')->group(function () {
            Route::post('getcategory', 'Products\ProductController@getCategory')->name('admin.getcategory');
            Route::get('/', 'DashboardController@index')->name('dashboard');
            Route::namespace('Products')->group(function () {
                Route::resource('products', 'ProductController');
                Route::get('remove-image-thumb/{id}', 'ProductController@removeThumbnail')->name('product.remove.thumb');
                Route::get('products-search', 'ProductController@index')->name('products.search');
                Route::get('stock-products', 'ProductController@stocklist')->name('stocklist.products');
                Route::get('editstock/products/{id}', 'ProductController@stockedit')->name('stockedit.products');
                Route::post('updatestock/products', 'ProductController@stockupdate')->name('stockupdate.products');
            });

            Route::namespace('Categories')->group(function () {
                Route::resource('categories', 'CategoryController');
                Route::get('remove-image-category', 'CategoryController@removeImage')->name('category.remove.image');
                Route::get('categories-search', 'CategoryController@index')->name('categories.search');
                Route::get('category-child/{parent_id}', 'CategoryController@childCategory')->name('category.child');
            });
            

            //News
            Route::get('news','News\NewsController@create')->name('news.create');
            Route::post('news-store','News\NewsController@store')->name('news.store');
            Route::get('news-list','News\NewsController@index')->name('news.list');
            Route::get('news/delete/{id}','News\NewsController@destroy')->name('news.destroy'); 
            Route::get('news/edit/{id}','News\NewsController@edit')->name('news.edit');
            Route::get('news-search','News\NewsController@index')->name('news.search');
            Route::post('news/status/{id}', 'News\NewsController@status')->name('news.status');

            
            Route::resource('employees', 'EmployeeController');
            Route::post('employees/is_active/{id}', 'EmployeeController@is_active')->name('employees.is_active');
            Route::get('profile/{id}', 'EmployeeController@getProfile')->name('employee.profile');
            Route::put('profile/{id}', 'EmployeeController@updateProfile')->name('employee.profile.update');
            Route::resource('permissions', 'Permissions\PermissionController');

            //CMS
            Route::get('cms-create','Cms\CmsController@create')->name('cms.create');
            Route::post('cms-store','Cms\CmsController@store')->name('cms.store');
            Route::get('cms','Cms\CmsController@index')->name('cms.list');
            Route::post('cms/delete/{id}','Cms\CmsController@destroy')->name('cms.destroy'); 
            Route::get('cms/edit/{id}','Cms\CmsController@edit')->name('cms.edit');
            Route::post('cms/status/{id}', 'Cms\CmsController@status')->name('news.status');

            //ContactUs
            Route::get('contactus-list','ContactusController@index')->name('contactus.list');
            Route::post('contactus/delete/{id}','ContactusController@destroy')->name('contactus.destroy'); 

    });    
});

/**
 * Frontend routes unused
 */

Route::namespace('Customer')->group(function () {
    Route::get('/', 'HomeController@index')->name('customer.home');
    // Contact Us
    Route::get('/contact-us', 'ContactUsController@index')->name('customer.contactus');
    Route::post('/contact-us/save', 'ContactUsController@store')->name('customer.contactus_save');

    // Gallery
    Route::get('/gallery', 'GalleryController@index')->name('customer.gallery');

    // Category Listing
    Route::get('/category-listing', 'CategoryController@index')->name('customer.category_listing');
    Route::post('/get-category-list', 'CategoryController@getCategoryList')->name('customer.get_category_list');
    Route::post('/get-product-model', 'CategoryController@getProductModel')->name('customer.get_product_model');

    // About us
    Route::get('/about-us', 'AboutController@index')->name('customer.aboutus');

    
});

app/Http/Controllers/Admin/Customers/CustomerController.php
<?php

namespace App\Http\Controllers\Admin\Customers;

use App\Shop\Customers\Customer;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Input;
use App\Helpers\RandomHelper;
use Auth;
use Log;
use Validator;
use App\Helpers\ResponseMessage;
use App\Shop\Dealers\Dealer;
use App\Shop\Customers\ForgetPassword;
use App\Shop\Cities\City;
use App\Shop\States\State;
use App\Helpers\MailHelper;
use App\Helpers\SMSHelper;
use App\Helpers\Permission;
use App\Shop\Customers\RequestPo;
use Carbon\Carbon;

class CustomerController extends Controller
{
    public function index(Request $request)
    {
        try{
            $permission = Permission::permission('users');
            if($permission->view==1 || $permission->add==1){
                $page=trim($request->page);
                $data['customers'] = DB::table('customers')
                        ->select('customers.*', 'states.name as state_name', 'cities.name as city_name', 'country.country as country_name')
                        ->leftjoin('country','country.id','customers.country')
                        ->leftjoin('states','states.id','customers.state')
                        ->leftjoin('cities','cities.id','customers.city')
                        ->OrderBy('customers.created_at','desc')
                        ->where('customers.deleted_at','=',null)
                        ->get();
                return view('admin.customers.list')->with($data);
                
            }else{
                return view('layouts.errors.403');
            }
        }
        catch(Exception $e){
                $Exceptions = New Exceptions;
                $Exceptions->sendException($e);  
        }
    }
    public function create()
    {
        try{
            $permission = Permission::permission('users');
            if($permission->add==1){
                $pass = RandomHelper::randomPassword();
                $rand = RandomHelper::randomID();
                $name = 'Hawk@'.$rand;
                return view('admin.customers.create',[
                    'password' => $pass,
                    'name' => $name
                ]);
            } else{
                return view('layouts.errors.403');
            }    
        }
        catch(Exception $e){
                $Exceptions = New Exceptions;
                $Exceptions->sendException($e);  
        }
    }
    public function edit($id) {
        try {
            $permission = Permission::permission('users');
            if($permission->edit==1){
                $customer = Customer::find($id);
                $data['customer'] = $customer;
                if($customer->city){
                    $data['cities'] = City::where('state_id', $customer->state)->get();
                }
                $data['states'] = State::get();
                return view('admin.customers.edit',$data);
            } else{
                return view('layouts.errors.403');
            }  
        } catch (Exception $e) {
            Log::errors($e);
        }
    }
    public function store(Request $request){
        try {
            $rules = [
                'user_id' => 'required|unique:customers',
                'phone' => 'required|numeric|unique:customers',
                'email' => 'required|unique:customers',
            ];
            $customeMessage = [
                'user_id.required' => 'Please enter user id.',
                'user_id.unique' => 'User id is already exists.',
                'phone.required' => 'Please enter user id.',
                'phone.unique' => 'Contact number is already exists.',
                'phone.numeric' => 'Please enter number',
                'email.required' => 'Please enter user id.',
                'email.unique' => 'Email is already exists.',
            ];
            $validator = Validator::make($request->all(),$rules, $customeMessage);

            if( $validator->fails() ) {
                return back()->withInput()->withErrors($validator->errors());
            } else {

                $customer = new Customer();
                $customer->user_id = $request->user_id;
                $customer->phone = $request->phone;
                $customer->password = $request->password;
                $customer->email = $request->email;
                $customer->is_active = $request->status;
                $customer->role = $request->role;
                $customer->organisation = "HAWK GRANITO PVT. LTD.";
                $customer->is_restricted = $request->is_restricted;
                $customer->status = 0;
                if($customer->save()){
                    if ($request->has('images')) {
                            $time      = md5(time());
                            $file      = $request->images;
                            $extension = $file->getClientOriginalExtension();
                            $image   = $time . '.' . $file->getClientOriginalExtension();
                            $file->move(public_path('customers/profile/'), $image);
                            $image                 = 'customers/profile/' . $image;
                            $image_update          = Customer::find($customer->id);
                            $image_update->profile = $image;
                            $image_update->save();
                    }       
                    $result = MailHelper::userIDMail($customer);
                    $sms = SMSHelper::sendUserIDPassword('91',$customer->phone,$customer->user_id,$customer->password );
                    return redirect()->route('admin.customers.index')->with('message', 'Customer add successfully.');
                }
            }
        } catch (Exception $e) {
            $Exceptions = New Exceptions;
            $Exceptions->sendException($e);
        }
    }
    public function update(Request $request, $id){
        try {
            $rules = [];
            $customeMessage = [
                'phone.required' => 'Please enter user id.',
                'phone.unique' => 'Contact number is already exists.',
                'phone.numeric' => 'Please enter number',
                'email.required' => 'Please enter user id.',
                'email.unique' => 'Email is already exists.',
            ];
            $customer_id = trim(strip_tags($id));
            if(Customer::where('id',$customer_id)->exists()){
                $customer = Customer::where('id',$customer_id)->get()->first();
                if($customer->phone!=trim(strip_tags($request->phone))){
                    $rules['phone'] = 'required|numeric|unique:customers';
                }
                if($customer->email!=trim(strip_tags($request->email))){
                    $rules['email'] = 'required|unique:customers';
                }
            }
            $validator = Validator::make($request->all(),$rules, $customeMessage);

            if( $validator->fails() ) {
                return back()->withInput()->withErrors($validator->errors());
            } else {
                // dd($request->all());
                if(Customer::find($id)->exists()) {
                    $customer = Customer::find($id);
                    $customer->phone = $request->phone;
                    $customer->role = $request->role;
                    if($request->password){
                        if($customer->password != $request->password){
                            $result = MailHelper::userIDMail($customer);
                            $sms = SMSHelper::sendUserIDPassword('91',$customer->phone,$customer->user_id,$customer->password );
                            ForgetPassword::where('userid',$customer->user_id)->delete();
                        }
                    }
                    $customer->email = $request->email;
                    $customer->is_active = $request->is_active;

                    $customer->name = $request->name;
                    $customer->country_code = 91;
                    $customer->organisation = $request->organisation;
                    $customer->address_line1 = $request->address_line1;
                    $customer->address_line2 = $request->address_line2;
                    $customer->country = $request->country;
                    $customer->state = $request->state;
                    $customer->city = $request->city;
                    $customer->post_code = $request->zip;
                    $customer->aadhar_card = $request->aadhar_card;
                    if (isset($request->is_restricted)) {
                        $customer->is_restricted = 0; 
                        $customer->restricted_time = null;
                    } else{
                        $date = date_default_timezone_set('Asia/Kolkata');
                        $customer->is_restricted = "1";
                        $customer->restricted_time = date('Y-m-d H:i:s');
                        if (RequestPo::where('customer_id',$customer->id)->exists()) {
                            RequestPo::where('customer_id',$customer->id)->delete();
                        }
                    }
                    if($request->gst_no){
                        $customer->gst_no = $request->gst_no;
                    } else {
                        $customer->gst_no = null;
                    }
                    $customer->status = $request->status;
                    $customer->notes =$request->notes;
                    if($customer->save()){
                        if ($request->has('background_image')) {
                            $time      = md5(time());
                            $file      = $request->background_image;
                            $extension = $file->getClientOriginalExtension();
                            $background_image   = $time . '.' . $file->getClientOriginalExtension();
                            $file->move(public_path('customers/gst/'), $background_image);

app/Http/Controllers/Admin/Customers/DealerController.php
<?php

namespace App\Http\Controllers\Admin\Customers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Shop\Customers\Customer;
use App\Shop\Dealers\Dealer;
use Carbon\Carbon;
use App\Helpers\Permission;

class DealerController extends Controller
{
    public function index(Request $request){
        try{
            $id = $request->id;
            $data['dealers'] = Dealer::select('dealers.*','customers.name as customer_name')
                            ->leftjoin('customers','customers.id','dealers.parent_id')
                            ->where('dealers.parent_id',$id)
                            ->where('dealers.status',0)
                            ->get();  
            $data['customer'] = Customer::where('id',$id)->first();
            return view('admin.customers.dealers.list')->with($data);
        } catch(Exception $e){
            Log::error($e);
        }
    }
    public function visiteddealer(){
        try{
            $permission = Permission::permission('visited_Dealer');
            if($permission->view==1 || $permission->add==1){
                $data['dealers'] = Dealer::select('dealers.*','customers.name as customer_name')
                                    ->leftjoin('customers','customers.id','dealers.parent_id')
                                    ->where('dealers.deleted_at',null)
                                    ->where('dealers.status',1)
                                    ->get();
                return view('admin.customers.dealers.visitedlist')->with($data);
            } else{
                return view('layouts.errors.403');
            }
        } catch(Exception $e){
            Log::error($e);
        }
    }
    public function destroy($id){
        try{
            $permission = Permission::permission('visited_Dealer');
            if($permission->delete==1){
                $dealer = Dealer::where('id',$id)->first();
                $dealer->deleted_at = date('Y-m-d H:i:s');
                $dealer->save();
                return back()->with('message', 'Dealer delete successfully.');
            } else{
                return view('layouts.errors.403');
            }
        } catch(Exception $e){
            Log::error($e);
        }
    }
}

app/Http/Controllers/Customer/AboutController.php
<?php

namespace App\Http\Controllers\Customer;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Shop\Cms\ContactUs;

class AboutController extends Controller
{
    public function index()
    {
    	$data['contactus'] = ContactUs::where('cms_id','!=',0)->first();
        return view('customers.aboutus')->with($data);
    }
}

resources/views/admin/customers/create.blade.php
@extends('layouts.admin-sol.app')

@section('content')
    <!-- Main content -->
    <section class="content">
        <!-- @include('layouts.errors-and-messages') -->
        <div class="container-fluid">
            <div class="row bg-title">
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                    <h4 class="page-title">Manage Users</h4>
                </div>
            </div>
            @include('layouts.errors-and-messages')
            <div class="page-content">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="customer-tab">                          
                            <ul class="nav nav-tabs" data-spy="affix" data-offset-top="135">
                                <li><a href="{{ route('admin.customers.index') }}">Users Listing</a></li>
                                <li class="active"><a data-toggle="tab">Add User</a></li>
                            </ul>
                            <div class="tab-content">
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                    <form action="{{ route('admin.customers.store') }}" id="create_customer" enctype="multipart/form-data" method="post" class="form">
                                        <div class="box-body">
                                            {{ csrf_field() }}
                                            <div class="form-group">
                                                <label for="user_id">User Id <span class="text-danger">*</span></label>
                                                <input type="text" name="user_id" id="user_id" placeholder="User Id" class="form-control" value="{{ $name }}" readonly="">
                                                @if ($errors->has('user_id'))
                                                    <span class="text-danger" style="color: red">{{ $errors->first('user_id') }}</span>
                                                @endif
                                            </div>
                                            <div class="form-group">
                                                <label for="email">Email <span class="text-danger">*</span></label>
                                                <div class="input-group">
                                                    <span class="input-group-addon">@</span>
                                                    <input type="text" name="email" id="email" placeholder="Email" class="form-control" value="{{ old('email') }}">
                                                </div>
                                                @if ($errors->has('email'))
                                                    <span class="text-danger" style="color: red">{{ $errors->first('email') }}</span>
                                                @endif
                                            </div>
                                            <div class="form-group">
                                                <label for="password">Password <span class="text-danger">*</span></label>
                                                <input type="text" name="password" id="password" value="{{ $password }}" class="form-control" readonly="">
                                            </div>
                                            <div class="form-group">
                                                <label for="phone">Mobile <span class="text-danger">*</span></label>
                                                <input type="text" name="phone" id="phone" placeholder="Mobile" class="form-control numeric" value="{{ old('phone') }}" maxlength="10">
                                                @if ($errors->has('phone'))
                                                    <span class="text-danger" style="color: red">{{ $errors->first('phone') }}</span>
                                                @endif
                                            </div>
                                            <div class="form-group">
                                                <label for="role">Role </label>
                                                <select name="role" id="role" class="form-control">
                                                    <option value="">Select</option>
                                                    <option value="0">Dealer</option>
                                                    <option value="1">Executive</option>
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <label for="status">Active </label>
                                                <select name="status" id="status" class="form-control">
                                                    <option value="">Select</option>
                                                    <option value="0">Disable</option>
                                                    <option value="1">Enable</option>
                                                </select>
                                            </div>
                                        </div>
                                        <!-- /.box-body -->
                                        <div class="box-footer">
                                            <div class="btn-group">
                                                <a href="{{ route('admin.products.index') }}" class="btn btn-default">Back</a>
                                                <button type="submit" class="btn btn-primary">Create</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->
@endsection

@section('js')
<script src="{{ asset('js/jquery.validate.js') }}"></script>
<script src="{{ asset('js/jquery.validate.min.js') }}"></script>
<script type="text/javascript">
    $('#images').bind('change', function () {
        var filename = $("#images").val();
        if (/^\s*$/.test(filename)) {
            $(".file-upload").find('#images').removeClass('active');
            $("#noFile").text("No file chosen...");
        }
        else {
            $(".file-upload").find('#images').addClass('active');
            $("#noFileBackground").text(filename.replace("C:\\fakepath\\", ""));
        }
    });
    $("#create_customer").validate({
        ignore: [],
        errorClass: 'error',
        successClass: 'validation-valid-label',
        highlight: function(element, errorClass) {
            $(element).removeClass(errorClass);
        },
        unhighlight: function(element, errorClass) {
            $(element).removeClass(errorClass);
        },
        validClass: "validation-valid-label",
        rules: {
            user_id: {
                required: true,
                maxlength: 25,
            },
            phone: {
                required: true,
                digits: true,
                minlength: 10,
                maxlength: 10,
            },
            email: {
                required: true,
                email: true,
            },
            password: {
                required: true,
                minlength: 8,
                maxlength: 15,
            },
            status : {
                required: true,
            }
        },
        messages: {
            "user_id":{
                required: "Please enter name.",
                // lettersonly: "Please enter only character.",
                maxlength: "Please enter max 25 character.",
            },
            "phone":{
                required: "Please enter mobile.",
                digits: "Please enter number only.",
                minlength: "Please enter min 10 digit.",
                maxlength: "Please enter max 10 digit.",
            },
            "email":{
                required: "Please enter email.",
                email: "Please enter a valid email address.",
            },
            "password":{
                required: "Please enter password.",
                minlength: "Please enter min 8 character.",
                maxlength: "Please enter max 15 character.",
            },
            "status":{
                required: "Please select status.",
            }
        },
        submitHandler: function(form) {
            $('button[type="submit"]').attr('disabled', true);
            form.submit();
        },
    });

    $('.numeric').on('input', function (event) {
        this.value = this.value.replace(/[^0-9]/g, '');
    });
</script>
@endsection

resources/views/admin/customers/forget-password.blade.php
@extends('layouts.admin-sol.app')
@section('content')

<!-- @include('layouts.errors-and-messages') -->
<div class="container-fluid">
    <div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">Request Password</h4>
        </div>
    </div>
    @include('layouts.errors-and-messages')
    <div class="page-content">
        <div class="row">
            <div class="col-sm-12">
                <div class="customer-tab">                          
                    <ul class="nav nav-tabs" data-spy="affix" data-offset-top="135">
                        <li class="active"><a data-toggle="tab" href="#CustomerListing">Users Listing</a></li>
                        @php
                            $permission = App\Helpers\Permission::permission('request_password');
                        @endphp
                    </ul>
                    <div class="tab-content">
                        <div id="CustomerListing" class="tab-pane fade in active">
                            <div class="manage-customer">
                                <table id="customer" class="table border-b1px" style="width:100%">
                                    <thead>
                                    <tr>
                                        <th>User Id</th>
                                        <th>Name</th>
                                        <th>E-mail</th>
                                        <th>Role</th>
                                        <th>State</th>
                                        <th>Phone</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @forelse ($customers as  $customer)
                                        @php
                                            $dealer = App\Shop\Dealers\Dealer::where('parent_id',$customer->id)->where('status',0)->get();            
                                        @endphp
                                        <tr>
                                            <td>{{ $customer->user_id }}</td>
                                            <td>{{ $customer->name }}</td>
                                            <td>{{ $customer->email }}</td>
                                            @if($customer->role==1)
                                            <td>Executive</td>
                                            @else
                                            <td>Dealers</td>
                                            @endif
                                            <td>{{ $customer->state_name }}</td>
                                            <td>{{ $customer->phone }}</td>
                                            <td>
                                                <form action="{{ route('admin.customers.destroy', $customer->id) }}" method="post" class="form-horizontal">
                                                    {{ csrf_field() }}
                                                    <input type="hidden" name="_method" value="delete">
                                                    <div class="action-btn">
                                                        @if($permission->edit==1)
                                                        <a href="{{ route('admin.customers.edit', $customer->id) }}" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i></a>
                                                        @endif
                                                    </div>
                                                </form>
                                            </td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="10" align="center">Data Not Found</td>
                                        </tr>
                                    @endforelse
                                    </tbody>
                                </table>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
<style type="text/css">
    .search{
        float: right!important;
        padding-bottom: 10px;
    }
    .btn-info, .btn-info.disabled {
        color: black!important;
        background: #e4e7ea!important;
    }
    .btn-info:hover{
        border:1px solid!important;
        border-color: none!important;
    }
</style>
@section('js')
<script>
    $(document).ready(function() {
        $('#customer').DataTable({
           "ordering": false
        });
    } );
</script>
@endsection