routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/** * Admin routes
 */
Route::namespace('Admin')->group(function () {
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'LoginController@login')->name('admin.login');
    Route::get('admin/logout', 'LoginController@logout')->name('admin.logout');
});
Route::group(['prefix' => 'admin', 'middleware' => ['employee'], 'as' => 'admin.' ], function () {
    Route::namespace('Admin')->group(function () {
            Route::post('getcategory', 'Products\ProductController@getCategory')->name('admin.getcategory');
            Route::get('/', 'DashboardController@index')->name('dashboard');
            Route::namespace('Products')->group(function () {
                Route::resource('products', 'ProductController');
                Route::get('remove-image-thumb/{id}', 'ProductController@removeThumbnail')->name('product.remove.thumb');
                Route::get('products-search', 'ProductController@index')->name('products.search');
                Route::get('stock-products', 'ProductController@stocklist')->name('stocklist.products');
                Route::get('editstock/products/{id}', 'ProductController@stockedit')->name('stockedit.products');
                Route::post('updatestock/products', 'ProductController@stockupdate')->name('stockupdate.products');
            });

            Route::namespace('Categories')->group(function () {
                Route::resource('categories', 'CategoryController');
                Route::get('remove-image-category', 'CategoryController@removeImage')->name('category.remove.image');
                Route::get('categories-search', 'CategoryController@index')->name('categories.search');
                Route::get('category-child/{parent_id}', 'CategoryController@childCategory')->name('category.child');
            });
            

            //News
            Route::get('news','News\NewsController@create')->name('news.create');
            Route::post('news-store','News\NewsController@store')->name('news.store');
            Route::get('news-list','News\NewsController@index')->name('news.list');
            Route::get('news/delete/{id}','News\NewsController@destroy')->name('news.destroy'); 
            Route::get('news/edit/{id}','News\NewsController@edit')->name('news.edit');
            Route::get('news-search','News\NewsController@index')->name('news.search');
            Route::post('news/status/{id}', 'News\NewsController@status')->name('news.status');

            
            Route::resource('employees', 'EmployeeController');
            Route::post('employees/is_active/{id}', 'EmployeeController@is_active')->name('employees.is_active');
            Route::get('profile/{id}', 'EmployeeController@getProfile')->name('employee.profile');
            Route::put('profile/{id}', 'EmployeeController@updateProfile')->name('employee.profile.update');
            Route::resource('permissions', 'Permissions\PermissionController');

            //CMS
            Route::get('cms-create','Cms\CmsController@create')->name('cms.create');
            Route::post('cms-store','Cms\CmsController@store')->name('cms.store');
            Route::get('cms','Cms\CmsController@index')->name('cms.list');
            Route::post('cms/delete/{id}','Cms\CmsController@destroy')->name('cms.destroy'); 
            Route::get('cms/edit/{id}','Cms\CmsController@edit')->name('cms.edit');
            Route::post('cms/status/{id}', 'Cms\CmsController@status')->name('news.status');

            //ContactUs
            Route::get('contactus-list','ContactusController@index')->name('contactus.list');
            Route::post('contactus/delete/{id}','ContactusController@destroy')->name('contactus.destroy'); 

    });    
});

/**
 * Frontend routes unused
 */

Route::namespace('Customer')->group(function () {
    Route::get('/', 'HomeController@index')->name('customer.home');
    // Contact Us
    Route::get('/contact-us', 'ContactUsController@index')->name('customer.contactus');
    Route::post('/contact-us/save', 'ContactUsController@store')->name('customer.contactus_save');

    // Gallery
    Route::get('/gallery', 'GalleryController@index')->name('customer.gallery');

    // Category Listing
    Route::get('/category-listing', 'CategoryController@index')->name('customer.category_listing');
    Route::post('/get-category-list', 'CategoryController@getCategoryList')->name('customer.get_category_list');
    Route::post('/get-product-model', 'CategoryController@getProductModel')->name('customer.get_product_model');

    // About us
    Route::get('/about-us', 'AboutController@index')->name('customer.aboutus');

    
});

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Shop\User;

class UserController extends Controller
{
    public function index()
    {
    	$data['users'] =  User::get();
    	$data['test'] ="test";
    	return view('admin.users.index')->with($data);
    }
}

resources/views/admin/users/index.blade.php
@extends('layouts.admin-sol.app')
@section('content')
	<div class="container-fluid">
		<div class="row bg-title">
			<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
				<h4 class="page-title">Manage CMS</h4>
			</div>
		</div>
		@include('layouts.errors-and-messages')
		
		<div class="page-content">
			<div class="row">
				<div class="col-sm-12">
					<div class="product-listing">
						<ul class="nav nav-tabs" data-spy="affix" data-offset-top="135">
							<!-- <li><a href="{{ route('admin.cms.create') }}">Add CMS</a></li> -->
							<li class="active"><a>CMS Listing</a></li>
					  	</ul>
					  	<div class="tab-content">
							<div id="ProductListing" class="tab-pane fade in active">
								<div class="product-listing">
									<div class="table-responsive">
										<table id="category" class="table border-b1px" style="width:100%">
											<thead>
												<tr>
													<th>Name</th>
													<th>Email</th>
													<th>Actions</th>
												</tr>
											</thead>
											<tbody>
											@forelse ($users as $user)
												<tr>
													<td>{{ $user->name }}</td>
													<td>{{ $user->email }}</td>
													<td>
														<div class="action-btn">
															<form action="{{ route('admin.cms.destroy', $user->id) }}" method="post" class="form-horizontal">
																{{ csrf_field() }}
																<div class="btn-group">
																	<a href="{{ route('admin.cms.edit', $user->id) }}" class="btn btn-edit"><i class="mdi mdi-pencil"></i></a>
																	<button onclick="return confirm('Are you sure?')" type="submit" class="btn btn-delete"><i class="mdi mdi-close"></i></button>
																</div>
															</form>
														</div>
													</td>
												</tr>
											@empty
												<tr>
													<td colspan="3" align="center">Data Not Found</td>
												</tr>
											@endforelse
											</tbody>
										</table>
									</div>
								</div>
							</div>
				  		</div>
					</div>
				</div>
			</div>
		</div>
	
</div>
@endsection
@section('css')
<style type="text/css">
	.btn-info, .btn-info.disabled {
        color: black!important;
        background: #e4e7ea!important;
    }
    .btn-info:hover{
        border:1px solid!important;
        border-color: none!important;
    }
</style>
@endsection
@section('js')
<script>
	$(document).ready(function() {
		var dataTable = $('#category').DataTable({
		});
		$("#date").change(function($e){

		date = $("#date").val();
		table = $("#category")[0].children[1].children;
		// dataTable.rows.table().data().add(date);
		 var data = dataTable.rows().table().data();
    	dataTable.draw();
	  //    	console.log(data);
		 // data.each(function (value, index) {
		 // 	// value = value[1].add('2');
	 	//     // value[1].('13');
	 	//     // value = value[1]+('123');
	 	//     // value[1].('13');
	 	    
		 // });
		// console.log(table);
		});
	} );
</script>
@endsection