routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/** * Admin routes
 */
Route::namespace('Admin')->group(function () {
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'LoginController@login')->name('admin.login');
    Route::get('admin/logout', 'LoginController@logout')->name('admin.logout');
});
Route::group(['prefix' => 'admin', 'middleware' => ['employee'], 'as' => 'admin.' ], function () {
    Route::namespace('Admin')->group(function () {
            Route::post('getcategory', 'Products\ProductController@getCategory')->name('admin.getcategory');
            Route::get('/', 'DashboardController@index')->name('dashboard');
            Route::namespace('Products')->group(function () {
                Route::resource('products', 'ProductController');
                Route::get('remove-image-thumb/{id}', 'ProductController@removeThumbnail')->name('product.remove.thumb');
                Route::get('products-search', 'ProductController@index')->name('products.search');
                Route::get('stock-products', 'ProductController@stocklist')->name('stocklist.products');
                Route::get('editstock/products/{id}', 'ProductController@stockedit')->name('stockedit.products');
                Route::post('updatestock/products', 'ProductController@stockupdate')->name('stockupdate.products');
            });

            Route::namespace('Categories')->group(function () {
                Route::resource('categories', 'CategoryController');
                Route::get('remove-image-category', 'CategoryController@removeImage')->name('category.remove.image');
                Route::get('categories-search', 'CategoryController@index')->name('categories.search');
                Route::get('category-child/{parent_id}', 'CategoryController@childCategory')->name('category.child');
            });
            

            //News
            Route::get('news','News\NewsController@create')->name('news.create');
            Route::post('news-store','News\NewsController@store')->name('news.store');
            Route::get('news-list','News\NewsController@index')->name('news.list');
            Route::get('news/delete/{id}','News\NewsController@destroy')->name('news.destroy'); 
            Route::get('news/edit/{id}','News\NewsController@edit')->name('news.edit');
            Route::get('news-search','News\NewsController@index')->name('news.search');
            Route::post('news/status/{id}', 'News\NewsController@status')->name('news.status');

            
            Route::resource('employees', 'EmployeeController');
            Route::post('employees/is_active/{id}', 'EmployeeController@is_active')->name('employees.is_active');
            Route::get('profile/{id}', 'EmployeeController@getProfile')->name('employee.profile');
            Route::put('profile/{id}', 'EmployeeController@updateProfile')->name('employee.profile.update');
            Route::resource('permissions', 'Permissions\PermissionController');

            //CMS
            Route::get('cms-create','Cms\CmsController@create')->name('cms.create');
            Route::post('cms-store','Cms\CmsController@store')->name('cms.store');
            Route::get('cms','Cms\CmsController@index')->name('cms.list');
            Route::post('cms/delete/{id}','Cms\CmsController@destroy')->name('cms.destroy'); 
            Route::get('cms/edit/{id}','Cms\CmsController@edit')->name('cms.edit');
            Route::post('cms/status/{id}', 'Cms\CmsController@status')->name('news.status');

            //ContactUs
            Route::get('contactus-list','ContactusController@index')->name('contactus.list');
            Route::post('contactus/delete/{id}','ContactusController@destroy')->name('contactus.destroy'); 

    });    
});

/**
 * Frontend routes unused
 */

Route::namespace('Customer')->group(function () {
    Route::get('/', 'HomeController@index')->name('customer.home');
    // Contact Us
    Route::get('/contact-us', 'ContactUsController@index')->name('customer.contactus');
    Route::post('/contact-us/save', 'ContactUsController@store')->name('customer.contactus_save');

    // Gallery
    Route::get('/gallery', 'GalleryController@index')->name('customer.gallery');

    // Category Listing
    Route::get('/category-listing', 'CategoryController@index')->name('customer.category_listing');
    Route::post('/get-category-list', 'CategoryController@getCategoryList')->name('customer.get_category_list');
    Route::post('/get-product-model', 'CategoryController@getProductModel')->name('customer.get_product_model');

    // About us
    Route::get('/about-us', 'AboutController@index')->name('customer.aboutus');

    
});

app/Http/Controllers/Admin/Categories/CategoryController.php
<?php

namespace App\Http\Controllers\Admin\Categories;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Shop\Categories\Category;
use Validator;
use Auth;
use Log;

class CategoryController extends Controller
{
    public function index(Request $request)
    {
        try{
            $data['categories'] = Category::select('categories.*')->orderBy('id','desc')->get();
            return view('admin.categories.list')->with($data);
        }
        catch (Exception $e) {
            log::debug($e);
        }
    }
    public function create()
    {
        try{
            $data['parent_categorys'] = Category::where('parent_id',0)->get();
            return view('admin.categories.create')->with($data);
        }
        catch (Exception $e) {
            Exceptions::exception($e);
        }
    }
    public function store(Request $request)
    {
        try{
            $rules =[
                'name' => 'required|string|max:255',
            ];
            $customeMessage = [
                'name.required' => 'Please enter name.',
            ];
            $validator = Validator::make($request->all(),$rules,$customeMessage);
            if( $validator->fails() ){
                return back()->withInput()->withErrors($validator->errors());
            } else{  
                $name = trim(strip_tags($request->name));
                $parent_id = trim(strip_tags($request->parent_id));
            }
            if($request->id!=""){
                $category=Category::find($request->id);
            }else{
                $category=New Category();
            }
            $category->name = $name;
            $category->parent_id = $parent_id;
            $category->save();
            if($request->id!=""){    
                return redirect()->route('admin.categories.index')->with('message', 'Category Update Succesfully.');
            }
            else{
                return redirect()->route('admin.categories.index')->with('message', 'Category Create Succesfully.');
            }
        }
        catch (Exception $e) {
            Exceptions::exception($e);
        }
    }
    public function edit($id)
    {
        try{
            if(Category::where('id',$id)->exists()){  
                $data['parent_categorys'] = Category::where('parent_id',0)->where('id','!=',$id)->get();
                $data['categories'] = Category::where('id',$id)->first();
                return view('admin.categories.create')->with($data);    
            }
        }
        catch(\Exception $e){
            $Exceptions = New Exceptions;
            $Exceptions->sendException($e);  
        }
    }
    public function destroy(int $id)
    {
        try{
            $cat_delete = Category::where('id',$id);
            $cat_delete->delete();
            return redirect()->route('admin.categories.index')->with('message', 'Category delete successfully.');
        }
        catch (Exception $e) {
            Exceptions::exception($e);
        }
    }
}

    

app/Http/Controllers/Customer/CategoryController.php
<?php

namespace App\Http\Controllers\Customer;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Shop\Categories\Category;
use App\Shop\Products\Product;

class CategoryController extends Controller
{
    public function index(Request $request)
    {
    	try {
    		$data['is_mobile'] = preg_match("/(android|avantgo|blackberry|bolt|boost|cricket|docomo|fone|hiptop|mini|mobi|palm|phone|pie|tablet|up\.browser|up\.link|webos|wos)/i", $_SERVER["HTTP_USER_AGENT"]);
    		$data['categorys'] =  Category::where('parent_id',0)->get();
    		$products = Category::select('categories.id as cat_id' , 'categories.name as cat_name','products.*')->leftjoin('products','products.category_id','categories.id');
            if ($request->id) {
                $products->where('categories.id',$request->id);
            }                        

    		$data['products'] = $products->where('products.status',1)->get();
            $data['category_id'] = $request->id;
            $data['category_name'] = Category::where('id',$request->id)->first();
	    	return view('customers/listing')->with($data);
    	} catch (Exception $e) {
    		Log::error($e);
    	}
    }
    public function getCategoryList(Request $request)
    {
    	try {
            $category_array = array();
			if ($request->id ) {
    			foreach ($request->id as $key => $id) {
    				$category =  Product::select('products.*','categories.id as cat_id' , 'categories.name as cat_name')
    								->leftjoin('categories','categories.id','products.category_id')
    								->where('categories.id',$id)
    								->where('products.status',1)
                                    ->with('product_image');
    				$category_array[] = $category->get();
    			}
			}else{
                $category_array[] =  Product::select('products.*','categories.id as cat_id' , 'categories.name as cat_name')
                                    ->leftjoin('categories','categories.id','products.category_id')
                                    ->where('products.status',1)
                                    ->with('product_image')
    								->get();
			}
			return view('customers.partial.filter',compact('category_array'));
    	} catch (Exception $e) {
    		Log::error($e);
    	}
    }
    public function getProductModel(Request $request){
        $product_array =  Product::select('products.*')
                                    ->where('products.id',$request->pro_id)
                                    ->where('products.status',1)
                                    ->with('product_image')
                                    ->first();
        return view('customers.partial.modal',compact('product_array'));                            
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.admin-sol.app')
@section('content')
	<div class="container-fluid">
		<div class="row bg-title">
			<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
				<h4 class="page-title">Manage Categories</h4> </div>
			<!-- <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
				<ol class="breadcrumb">
					<li><a href="#">Manage Products</a></li>
					<li class="active">Add Products</li>
				</ol>
			</div> -->
			<!-- /.col-lg-12 -->
		</div>
		<div class="page-content">
			<div class="row">
				<div class="col-sm-12">
					
					<div class="product-tab">
						<ul class="nav nav-tabs" data-spy="affix" data-offset-top="135">
							@if(isset($categories->id))
								<li class="active"><a>Edit Category</a></li>
							@else
								<li class="active"><a>Add Category</a></li>
							@endif
							<li><a href="{{ route('admin.categories.index') }}">Categories Listing</a></li>
					  </ul>
					  <div class="tab-content">
							<div id="AddProcucts" class="tab-pane fade in active">
								<div class="add-product">
								  <form action="{{ route('admin.categories.store') }}" method="post" class="form" enctype="multipart/form-data">
									@csrf
		                			@if(isset($categories->id))
				            			<input type="hidden" name="id" value="{{$categories->id}}">
		            				@else
				            			<input type="hidden" name="id" value="">
			            			@endif
			            			<div class="row">
			            				<div class="col-sm-6 col-md-6 col-sm-6 col-xs-12">
											<div class="form-group">
												<label>Select Category</label>
												<select name="parent_id" id="parent_id" class="form-control" style="width: 100%; height:36px;">
													<option value="">Select Category</option>
													@foreach($parent_categorys as $data)
														<option value="{{ $data->id }}"
														@if(old('parent_id') == $data->id)
                                						selected="true"
                                						@endif
				                                        @if(isset($categories->parent_id) && $data->id== $categories->parent_id))
				                                            selected="true"
				                                        @endif
				                                        
				                                        >{{ $data->name }}</option>
				                                    @endforeach
												</select>
												@if($errors->has('parent_id'))
	                                      			<span class="text-danger">{{$errors->first('parent_id')}}</span>
	                                    		@endif
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-sm-6 col-md-6 col-sm-6 col-xs-12">
											<div class="form-group">
												<label>Name<span class="red">*</span></label>
												<input type="text" class="form-control" name="name" id="name" value="@if(isset($categories->name)){{$categories->name}}@elseif(old('name')!=''){{old('name')}} @endif" maxlength="50" placeholder="Enter Category Name">
												@if($errors->has('name'))
	                                      			<span class="text-danger">{{$errors->first('name')}}</span>
	                                    		@endif
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-sm-12">
											<hr style="height: 1px; background: #e4e4e4;">
										</div>
										<div class="col-sm-12">
											<div class="submit-btn">
												<button type="submit" class="btn btn-submit">Submit</button>
											</div>
										</div>
									</div>
								</form>
							</div>
					  	</div>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection
@push('js')
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>-->
<script type="text/javascript">
$(document).ready(function() {
	$('#cover').bind('change', function () {
		var filename = $("#cover").val();
		if (/^\s*$/.test(filename)) {
			$(".file-upload").find('#cover').removeClass('active');
			$("#noFile").text("No file chosen...");
		}
		else {
			$(".file-upload").find('#cover').addClass('active');
			$("#noFile").text(filename.replace("C:\\fakepath\\", ""));
		}
	});
});
</script>
@endpush

resources/views/admin/categories/list.blade.php
@extends('layouts.admin-sol.app')
@section('content')
	<div class="container-fluid">
		<div class="row bg-title">
			<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
				<h4 class="page-title">Manage Categories</h4>
			</div>
		</div>
		@include('layouts.errors-and-messages')
		@if($categories)
		<div class="page-content">
			<div class="row">
				<div class="col-sm-12">
					<div class="product-listing">
						<ul class="nav nav-tabs" data-spy="affix" data-offset-top="135">
							<li><a href="{{ route('admin.categories.create') }}">Add Category</a></li>
							<li class="active"><a>Categories Listing</a></li>
					  	</ul>
					  	<div class="tab-content">
					  		
							<div id="ProductListing" class="tab-pane fade in active">
								<div class="product-listing">
									<div class="table-responsive">
										<table id="category" class="table border-b1px" style="width:100%">
											<thead>
												<tr>
													<th>Name</th>
													<th>Parent Category</th>
													<th>Actions</th>
												</tr>
											</thead>
											<tbody>
											@forelse ($categories as $category)
												@php
													$parentcat = DB::table('categories')->where('id',$category->parent_id)->first();
												@endphp
												<tr>
													<td>{{ $category->name }}</td>
													<td>@if($parentcat) {{ $parentcat->name }} @endif</td>
													<td>
														<div class="action-btn">
															<form action="{{ route('admin.categories.destroy', $category->id) }}" method="post" class="form-horizontal">
																{{ csrf_field() }}
																<input type="hidden" name="_method" value="delete">
																<div class="btn-group">
																	<a href="{{ route('admin.categories.edit', $category->id) }}" class="btn btn-edit"><i class="mdi mdi-pencil"></i></a>
																	<button onclick="return confirm('Are you sure?')" type="submit" class="btn btn-delete"><i class="mdi mdi-close"></i></button>
																</div>
															</form>
														</div>
													</td>
												</tr>
											@empty
												<tr>
													<td colspan="3" align="center">Data Not Found</td>
												</tr>
											@endforelse
											</tbody>
										</table>
								</div>
							</div>
						</div>
				  	</div>
				</div>
			</div>
		</div>
	</div>
	@endif
</div>
@endsection
@section('css')
<style type="text/css">
	.btn-info, .btn-info.disabled {
        color: black!important;
        background: #e4e7ea!important;
    }
    .btn-info:hover{
        border:1px solid!important;
        border-color: none!important;
    }
</style>
@endsection
@section('js')
<script>
	$(document).ready(function() {
		var dataTable = $('#category').DataTable({
		});
		$("#date").change(function($e){

		date = $("#date").val();
		table = $("#category")[0].children[1].children;
		// dataTable.rows.table().data().add(date);
		 var data = dataTable.rows().table().data();
    	dataTable.draw();
	  //    	console.log(data);
		 // data.each(function (value, index) {
		 // 	// value = value[1].add('2');
	 	//     // value[1].('13');
	 	//     // value = value[1]+('123');
	 	//     // value[1].('13');
	 	    
		 // });
		// console.log(table);
		});
	} );
</script>
@endsection